services:
  extract:
    build: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python src/extract.py

  transform:
    build: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python src/transform.py

  quality:
    build: .
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python src/quality_checks.py

  upload:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    command: python src/upload_to_blob.py